### ISSUE TITLE
don't open every app in a new window, keep them in the same window

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#326] opened 2018-01-30 21:54 UTC
Community request:

don't open every app in a new window, keep them in the same window

**Comment by brianmcmichael** [comment] 2018-01-30 21:56
Note:

This was a deliberate design decision. OnDemand-branded apps open in the same tab, non-branded apps (file explorer, shell, editor, etc.) open in new tabs.

**Comment by ericfranz** [comment] 2018-12-17 16:16
duplicate of https://github.com/OSC/ood-dashboard/issues/430

**Closed by ericfranz** 2018-12-17 16:16 UTC
Labels: community request, duplicate
